services:
  backend:
    build: ./back
    ports:
      - "5000:5000"
    volumes:
      - biblioteca:/app/datos

  frontend:
    build: ./front
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  biblioteca:
